name: 'wiz-cli'
on: [push]

jobs:
  wiz-cli-iac-scan:
    name: 'send email github'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "." # Set the relative path in the repo to scan
      POLICY: "IaC-policy-zero-high" # Set the desired Wiz-cli policy to use
      HOME: "home/ec2-user" # Set the runner home directory for wiz cli 

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:      
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: email-smtp.us-east-1.amazonaws.com
        server_port: 465
    # user credentials
        username: AKIAWAYEGMNGGP5ZUR6W
        password: BABqdnCmPSJ47UrC70wUugeFmukCTR5fH/yJiZkHMGr9
    # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
        to: Arya_Ray@newyorklife.com,ravi_kumar1@newyorklife.com,sandeepkumar_das@newyorklife.com
    # from email name
        from: '"ravi" <ravi_kumar1@newyorklife.com>'
